#!/usr/bin/env python3
"""Writes backends/redcore_battle_gfx.h: the real game font / battle-HUD tiles and the species,
move and type name tables, so redcore can draw the battle screen the way the emulator does.

Tile art comes from the disassembly's gfx/font/font.png (codes 0x80-0xFF) and
gfx/font/font_battle_extra.png (codes 0x62-0x78 in battle: HP bar, :L, ...; its last tiles are
ball icons) and gfx/font/font_extra.png (codes 0x60-0x7F; 0x79-0x7E are the text-box borders). Names come from
data/pokemon/names.asm and data/moves/names.asm (both in internal-index order). Pixels are the
emulator's four grays (0/85/170/255). Pure stdlib; no PIL needed."""
import re, struct, sys, zlib

ROOT = sys.argv[1] if len(sys.argv) > 1 else "vendor/pokered"
OUT = sys.argv[2] if len(sys.argv) > 2 else "ocean/pokered/backends/redcore_battle_gfx.h"


def read_png(path):
    d = open(path, "rb").read()
    assert d[:8] == b"\x89PNG\r\n\x1a\n"
    pos, idat, plte = 8, b"", None
    while pos < len(d):
        n, t = struct.unpack(">I4s", d[pos:pos + 8])
        body = d[pos + 8:pos + 8 + n]
        pos += 12 + n
        if t == b"IHDR":
            w, h, depth, ctype, _, _, interlace = struct.unpack(">IIBBBBB", body)
            assert interlace == 0 and ctype in (0, 3), (path, ctype)
        elif t == b"PLTE":
            plte = [body[i] for i in range(0, len(body), 3)]  # red channel; the art is gray
        elif t == b"IDAT":
            idat += body
    raw = zlib.decompress(idat)
    stride = (w * depth + 7) // 8
    rows, prev = [], bytearray(stride)
    for y in range(h):
        f = raw[y * (stride + 1)]
        line = bytearray(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        bpp = max(1, depth // 8)
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 1: line[i] = (line[i] + a) & 255
            elif f == 2: line[i] = (line[i] + b) & 255
            elif f == 3: line[i] = (line[i] + ((a + b) >> 1)) & 255
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[i] = (line[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
        prev = line
        px = []
        for x in range(w):
            if depth == 8: v = line[x]
            else:
                bit = x * depth
                v = (line[bit // 8] >> (8 - depth - bit % 8)) & ((1 << depth) - 1)
            if ctype == 3: v = plte[v]
            elif depth < 8: v = v * 255 // ((1 << depth) - 1)
            px.append(v)
        rows.append(px)
    return w, h, rows


def shade(v):
    return (0, 85, 170, 255)[min(3, (v + 42) // 85)]


def tiles(path):
    w, h, rows = read_png(path)
    out = []
    for ty in range(h // 8):
        for tx in range(w // 8):
            out.append([shade(rows[ty * 8 + y][tx * 8 + x]) for y in range(8) for x in range(8)])
    return out


def grid(name, ts):
    s = [f"static const uint8_t {name}[{len(ts)}][64] = {{"]
    for t in ts:
        s.append("    {" + ",".join(str(v) for v in t) + "},")
    s.append("};")
    return s


def names(path, pattern, fix):
    return [fix(m) for m in re.findall(pattern, open(path, encoding="utf-8").read())]


def fix(s):  # the font's special glyphs travel as octal escapes: \001 e-acute, \002 male, \003 female
    s = s.replace("\u00e9", "\x01").replace("\u2642", "\x02").replace("\u2640", "\x03")
    return re.sub(r"[^\x20-\x7e\x01-\x03]", "", s)


mons = names(f"{ROOT}/data/pokemon/names.asm", r'dname "([^"]*)"', fix)
trainers = names(f"{ROOT}/data/trainers/names.asm", r'li "([^"]*)"', fix)
moves = names(f"{ROOT}/data/moves/names.asm", r'li "([^"]*)"', fix)
types = ["NORMAL", "FIGHTING", "FLYING", "POISON", "GROUND", "ROCK", "BIRD", "BUG", "GHOST"] + ["NORMAL"] * 11 + \
        ["FIRE", "WATER", "GRASS", "ELECTRIC", "PSYCHIC", "ICE", "DRAGON"]

L = ["#ifndef REDCORE_OCEAN_BATTLE_GFX_H", "#define REDCORE_OCEAN_BATTLE_GFX_H", "",
     "// GENERATED by tools/gen_battle_gfx.py from the pokered disassembly -- do not edit.", "",
     "#include <stdint.h>", ""]
L.append("// font.png: tile i is character code 0x80 + i.")
L += grid("RC_FONT_TILES", tiles(f"{ROOT}/gfx/font/font.png"))
L.append("// battle_hud_1..3.png: tiles 0-2 are codes 0x6D-0x6F, tiles 3-8 are 0x73-0x78 (they replace the"
         " same codes of font_battle_extra while a battle is on screen).")
L += grid("RC_BATTLE_HUD_TILES", sum((tiles(f"{ROOT}/gfx/battle/battle_hud_{i}.png") for i in (1, 2, 3)), []))
L.append("// font_extra.png: tile i is character code 0x60 + i (0x79-0x7E: text-box borders).")
L += grid("RC_FONT_EXTRA_TILES", tiles(f"{ROOT}/gfx/font/font_extra.png"))
L.append("// font_battle_extra.png: tile i is character code 0x62 + i (HP bar, :L; only 0x62-0x78 are used).")
L += grid("RC_BATTLE_EXTRA_TILES", tiles(f"{ROOT}/gfx/font/font_battle_extra.png"))
L.append("")
_, _, red = read_png(f"{ROOT}/gfx/player/redb.png")
L.append("// redb.png: the player's 32x32 back pic, shown (doubled) until the first mon is sent out.")
L.append("static const uint8_t RC_PLAYER_BACK_PIC[32 * 32] = {" + ",".join(str(shade(v)) for row in red for v in row) + "};")
L.append("")
for var, lst in (("RC_SPECIES_NAMES", mons), ("RC_MOVE_NAMES", moves), ("RC_TYPE_NAMES", types),
                 ("RC_TRAINER_NAMES", trainers)):
    L.append(f"// {var}: species/move names are indexed by id - 1, trainer class names by class index.")
    L.append(f"#define {var}_COUNT {len(lst)}")
    L.append(f"static const char *const {var}[] = {{")
    L += ['    "' + "".join(f"\\{ord(c):03o}" if ord(c) < 8 else c for c in n) + '",' for n in lst]
    L.append("};")
    L.append("")
L.append("#endif")
open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT}: {len(mons)} species, {len(moves)} moves")
