[base]
package = ocean
env_name = puffer_mgba
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8
batch_size = auto

[env]
num_envs = 8
rom_path = "./pokemon_red.gb"
stream_enabled = True,
stream_interval = 400
stream_user = "leanke\n",
stream_color = "#800080",
stream_extra = "W-E: "
max_episode_length = 20480
; BLUE = "#0000FF"
; GREEN = "#00A36C"
; RED = "#FF0000"
; PURPLE = "#800080"
; PINK = "#FF00FF"
; YELLOW = "#DAEE01"

[train]
total_timesteps = 100_000_000
; update_epochs = 3
gamma = 0.998
; bptt_horizon = 64
minibatch_size = 2048
compile = False
compile_mode = reduce-overhead
compile_fullgraph = False
anneal_lr =  False
device = cuda
learning_rate = 0.005


