[base]
package = ocean
env_name = puffer_mgba
policy_name = Policy
rnn_name = Recurrent

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[vec]
num_envs = 24
batch_size = auto

[env]
num_envs = 4
rom_path = "./pokemon_red.gb"
; frameskip = 4,
; max_episode_length = 10_000,
stream_enabled = True,
stream_user = "leanke@ini",
stream_color = "#FF0000",
stream_extra = "something"
; BLUE = "#0000FF"
; GREEN = "#00A36C"
; RED = "#FF0000"
; PURPLE = "#800080"
; PINK = "#FF00FF"
; YELLOW = "#DAEE01"

[train]
total_timesteps = 1_000_000
update_epochs = 3
gamma = 0.998
; batch_size = auto
bptt_horizon = 64
minibatch_size = 2048
compile = False
learning_rate = 2.0e-4
anneal_lr = False
swarm = False
device = cuda
plot_activations = False
save_embeddings = False
