#ifndef POKERED_RAM_MAP_H
#define POKERED_RAM_MAP_H

#include <stdint.h>

#define PKRED_BE16(hi, lo) ((uint16_t)(((uint16_t)(hi) << 8) | (uint8_t)(lo)))

#if defined(__GNUC__) || defined(__clang__)
#  define PKRED_PACKED __attribute__((packed))
#else
#  define PKRED_PACKED
#endif
#ifdef _MSC_VER
#  pragma pack(push, 1)
#endif

typedef struct PKRED_PACKED {
    uint8_t species;
    uint8_t hp_hi, hp_lo;
    uint8_t box_level;
    uint8_t status;
    uint8_t type1, type2;
    uint8_t catch_rate;
    uint8_t moves[4];
    uint8_t ot_id_hi, ot_id_lo;
    uint8_t exp[3];
    uint8_t hp_exp_hi, hp_exp_lo;
    uint8_t attack_exp_hi, attack_exp_lo;
    uint8_t defense_exp_hi, defense_exp_lo;
    uint8_t speed_exp_hi, speed_exp_lo;
    uint8_t special_exp_hi, special_exp_lo;
    uint8_t dv_hi, dv_lo;
    uint8_t pp[4];
    uint8_t level;
    uint8_t max_hp_hi, max_hp_lo;
    uint8_t attack_hi, attack_lo;
    uint8_t defense_hi, defense_lo;
    uint8_t speed_hi, speed_lo;
    uint8_t special_hi, special_lo;
} PkredPartyMon;

#ifdef _MSC_VER
#  pragma pack(pop)
#endif

#if __STDC_VERSION__ >= 201112L
#  include <assert.h>
   static_assert(sizeof(PkredPartyMon) == 0x2C, "PkredPartyMon size mismatch");
#endif

#define PKRED_ADDR_PARTY_MON1 0xD16Bu
#define PKRED_PARTY_MON_STRIDE 0x2Cu
#define PKRED_ADDR_PARTY_MON(n) (PKRED_ADDR_PARTY_MON1 + (n) * PKRED_PARTY_MON_STRIDE)

#define PKRED_ADDR_CUR_MAP            0xD35Eu
#define PKRED_ADDR_Y_COORD            0xD361u
#define PKRED_ADDR_X_COORD            0xD362u

#define PKRED_ADDR_PARTY_COUNT   0xD163u

#define PKRED_ADDR_IS_IN_BATTLE      0xD057u
#define PKRED_ADDR_BATTLE_TYPE       0xD05Au

#define PKRED_ADDR_BATTLE_MON_SPECIES   0xD014u
#define PKRED_ADDR_BATTLE_MON_HP        0xD015u
#define PKRED_ADDR_BATTLE_MON_STATUS    0xD018u
#define PKRED_ADDR_BATTLE_MON_LEVEL     0xD022u
#define PKRED_ADDR_BATTLE_MON_MAX_HP    0xD023u
#define PKRED_ADDR_ENEMY_MON_SPECIES    0xCFE5u
#define PKRED_ADDR_ENEMY_MON_HP         0xCFE6u
#define PKRED_ADDR_ENEMY_MON_STATUS     0xCFE9u
#define PKRED_ADDR_ENEMY_MON_LEVEL      0xCFF3u
#define PKRED_ADDR_ENEMY_MON_MAX_HP     0xCFF4u
#define PKRED_ADDR_ESCAPED_FROM_BATTLE  0xD078u
#define PKRED_ADDR_PLAYER_SELECTED_MOVE 0xCCDCu

#define PKRED_ADDR_BATTLE_MON_TYPE1 0xD019u
#define PKRED_ADDR_BATTLE_MON_TYPE2 0xD01Au
#define PKRED_ADDR_BATTLE_MON_MOVES 0xD01Cu
#define PKRED_ADDR_BATTLE_MON_PP    0xD02Du
#define PKRED_ADDR_ENEMY_MON_TYPE1  0xCFEAu
#define PKRED_ADDR_ENEMY_MON_TYPE2  0xCFEBu

#define PKRED_STATUS_PSN_BIT 3u
#define PKRED_STATUS_BRN_BIT 4u
#define PKRED_STATUS_FRZ_BIT 5u
#define PKRED_STATUS_PAR_BIT 6u

#define PKRED_ADDR_PLAYER_MONEY   0xD347u
#define PKRED_ADDR_OBTAINED_BADGES 0xD356u
#define PKRED_ADDR_POKEDEX_OWNED  0xD2F7u
#define PKRED_ADDR_POKEDEX_SEEN   0xD30Au
#define PKRED_POKEDEX_NUM_POKEMON 151
#define PKRED_ADDR_LAST_BLACKOUT_MAP 0xD719u

#define PKRED_NUM_BADGES 8
#define PKRED_BADGE_BIT_BOULDER 0u
#define PKRED_BADGE_BIT_CASCADE 1u
#define PKRED_BADGE_BIT_THUNDER 2u
#define PKRED_BADGE_BIT_RAINBOW 3u
#define PKRED_BADGE_BIT_SOUL    4u
#define PKRED_BADGE_BIT_MARSH   5u
#define PKRED_BADGE_BIT_VOLCANO 6u
#define PKRED_BADGE_BIT_EARTH   7u

#define PKRED_ADDR_NUM_BAG_ITEMS 0xD31Du
#define PKRED_ADDR_BAG_ITEMS     0xD31Eu
#define PKRED_BAG_ITEM_CAPACITY  20

#define PKRED_ITEM_MASTER_BALL   0x01u
#define PKRED_ITEM_ULTRA_BALL    0x02u
#define PKRED_ITEM_GREAT_BALL    0x03u
#define PKRED_ITEM_POKE_BALL     0x04u
#define PKRED_ITEM_TOWN_MAP      0x05u
#define PKRED_ITEM_BICYCLE       0x06u
#define PKRED_ITEM_SAFARI_BALL   0x08u
#define PKRED_ITEM_ANTIDOTE      0x0Bu
#define PKRED_ITEM_BURN_HEAL     0x0Cu
#define PKRED_ITEM_ICE_HEAL      0x0Du
#define PKRED_ITEM_AWAKENING     0x0Eu
#define PKRED_ITEM_PARLYZ_HEAL   0x0Fu
#define PKRED_ITEM_FULL_RESTORE  0x10u
#define PKRED_ITEM_MAX_POTION    0x11u
#define PKRED_ITEM_HYPER_POTION  0x12u
#define PKRED_ITEM_SUPER_POTION  0x13u
#define PKRED_ITEM_POTION        0x14u
#define PKRED_ITEM_ESCAPE_ROPE   0x1Du
#define PKRED_ITEM_REPEL         0x1Eu
#define PKRED_ITEM_OLD_AMBER     0x1Fu
#define PKRED_ITEM_DOME_FOSSIL   0x29u
#define PKRED_ITEM_HELIX_FOSSIL  0x2Au
#define PKRED_ITEM_SECRET_KEY    0x2Bu
#define PKRED_ITEM_BIKE_VOUCHER  0x2Du
#define PKRED_ITEM_CARD_KEY      0x30u
#define PKRED_ITEM_FULL_HEAL     0x34u
#define PKRED_ITEM_REVIVE        0x35u
#define PKRED_ITEM_MAX_REVIVE    0x36u
#define PKRED_ITEM_S_S_TICKET    0x3Fu
#define PKRED_ITEM_GOLD_TEETH    0x40u
#define PKRED_ITEM_COIN_CASE     0x45u
#define PKRED_ITEM_OAKS_PARCEL   0x46u
#define PKRED_ITEM_SILPH_SCOPE   0x48u
#define PKRED_ITEM_POKE_FLUTE    0x49u
#define PKRED_ITEM_LIFT_KEY      0x4Au
#define PKRED_ITEM_ETHER         0x50u
#define PKRED_ITEM_MAX_ETHER     0x51u
#define PKRED_ITEM_ELIXER        0x52u
#define PKRED_ITEM_MAX_ELIXER    0x53u
#define PKRED_ITEM_HM01_CUT      0xC4u
#define PKRED_ITEM_HM02_FLY      0xC5u
#define PKRED_ITEM_HM03_SURF     0xC6u
#define PKRED_ITEM_HM04_STRENGTH 0xC7u
#define PKRED_ITEM_HM05_FLASH    0xC8u

#define PKRED_BAG_TRACKED_ITEMS 23
static const uint8_t PKRED_BAG_TRACKED_ITEM_IDS[PKRED_BAG_TRACKED_ITEMS] = {
    PKRED_ITEM_MASTER_BALL, PKRED_ITEM_ULTRA_BALL, PKRED_ITEM_GREAT_BALL,
    PKRED_ITEM_POKE_BALL, PKRED_ITEM_SAFARI_BALL,
    PKRED_ITEM_POTION, PKRED_ITEM_SUPER_POTION, PKRED_ITEM_HYPER_POTION,
    PKRED_ITEM_MAX_POTION, PKRED_ITEM_FULL_RESTORE,
    PKRED_ITEM_REVIVE, PKRED_ITEM_MAX_REVIVE, PKRED_ITEM_FULL_HEAL,
    PKRED_ITEM_ANTIDOTE, PKRED_ITEM_BURN_HEAL, PKRED_ITEM_ICE_HEAL,
    PKRED_ITEM_AWAKENING, PKRED_ITEM_PARLYZ_HEAL,
    PKRED_ITEM_ETHER, PKRED_ITEM_MAX_ETHER, PKRED_ITEM_ELIXER, PKRED_ITEM_MAX_ELIXER,
    PKRED_ITEM_ESCAPE_ROPE,
};

#define PKRED_KEY_ITEMS 16
static const uint8_t PKRED_KEY_ITEM_IDS[PKRED_KEY_ITEMS] = {
    PKRED_ITEM_TOWN_MAP, PKRED_ITEM_BICYCLE, PKRED_ITEM_OLD_AMBER,
    PKRED_ITEM_DOME_FOSSIL, PKRED_ITEM_HELIX_FOSSIL, PKRED_ITEM_SECRET_KEY,
    PKRED_ITEM_BIKE_VOUCHER, PKRED_ITEM_CARD_KEY, PKRED_ITEM_S_S_TICKET,
    PKRED_ITEM_GOLD_TEETH, PKRED_ITEM_COIN_CASE, PKRED_ITEM_OAKS_PARCEL,
    PKRED_ITEM_SILPH_SCOPE, PKRED_ITEM_POKE_FLUTE, PKRED_ITEM_LIFT_KEY,
    PKRED_ITEM_SAFARI_BALL,
};

#define PKRED_ADDR_PLAYER_SPRITE_FACING_DIRECTION 0xC109u

#define PKRED_MOVE_CUT      15u
#define PKRED_MOVE_FLY      19u
#define PKRED_MOVE_SURF     57u
#define PKRED_MOVE_STRENGTH 70u
#define PKRED_MOVE_FLASH    148u

#define PKRED_ADDR_VIRIDIAN_CITY_CUR_SCRIPT 0xD5F4u
#define PKRED_ADDR_WD72E                    0xD72Eu
#define PKRED_WD72E_DISABLE_BATTLES_BIT     4
#define PKRED_ADDR_ROUTE22_RIVAL_EVENTS         0xD7EBu
#define PKRED_ROUTE22_RIVAL_TRIGGER_1ST_BIT     0
#define PKRED_ROUTE22_RIVAL_TRIGGER_2ND_BIT     1
#define PKRED_ROUTE22_RIVAL_BEAT_1ST_BIT        5
#define PKRED_ROUTE22_RIVAL_BEAT_2ND_BIT        6
#define PKRED_ROUTE22_RIVAL_WANTS_BATTLE_BIT    7

#define PKRED_ADDR_MISSABLE_OBJECT_FLAGS        0xD5A6u
#define PKRED_MISSABLE_HS_ROUTE_22_RIVAL_1      0x22u
#define PKRED_MISSABLE_HS_ROUTE_22_RIVAL_2      0x23u

#endif
