#ifndef REDCORE_OCEAN_START_H
#define REDCORE_OCEAN_START_H

// GENERATED by ocean/pokered/tests/run_all.sh start from the emulator start state -- do not edit.
// RAM of the emulator backend right after reset: the ground truth redcore's
// fixed start is built from (see redcore_reset_to_fixed_start).

#define RC_START_MAP 0
#define RC_START_X 9
#define RC_START_Y 7
#define RC_START_FACING_BYTE 4  // sprite facing: 0 down, 4 up, 8 left, 12 right
#define RC_START_BADGES 0x00
#define RC_START_MONEY 2575
#define RC_START_PLAYER_NAME "AAAAAAA"
#define RC_START_RIVAL_NAME "ASSSSSS"

typedef struct RcStartMon {
    uint8_t species, level, status, catch_rate;
    uint16_t hp, max_hp, attack, defense, speed, special, ot_id;
    uint32_t exp;
    uint16_t stat_exp[5];  // hp, attack, defense, speed, special
    uint8_t dv_hi, dv_lo;  // packed: atk|def, spd|spc
    uint8_t moves[4], pp[4];
} RcStartMon;

#define RC_START_PARTY_COUNT 1
static const RcStartMon RC_START_PARTY[] = {
    {153, 6, 0, 45, 23, 23, 11, 11, 12, 14, 44980, 204, {39, 52, 43, 65, 50}, 0x75, 0xDB, {33, 45, 0, 0}, {35, 40, 0, 0}},
};

#define RC_START_BAG_COUNT 2
static const uint8_t RC_START_BAG[][2] = {  // ROM item id, quantity
    {4, 3},
    {5, 1},
};

// Pokedex bitmaps, bit (dex number - 1).
static const uint8_t RC_START_DEX_OWNED[19] = {0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static const uint8_t RC_START_DEX_SEEN[19] = {0x09, 0x80, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

// Object toggles (ShowObject/HideObject state): bit set = hidden. 32 bytes from 0xD5A6.
static const uint8_t RC_START_TOGGLES[32] = {0xA3, 0x00, 0x7E, 0x01, 0x88, 0xAE, 0x03, 0x00, 0x10, 0x10, 0x00, 0x00, 0x0C, 0x00, 0x02, 0x00, 0x80, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x9E, 0x07, 0x00, 0x00, 0x00};

// Set story events (names from includes/events.h).
static const char *const RC_START_EVENTS[] = {
    "Followed Oak Into Lab",
    "Got Town Map",
    "Entered Blues House",
    "Daisy Walking",
    "Followed Oak Into Lab 2",
    "Oak Asked To Choose Mon",
    "Got Starter",
    "Battled Rival In Oaks Lab",
    "Got Pokedex",
    "Oak Appeared In Pallet",
    "Oak Got Parcel",
    "Got Oaks Parcel",
};
#define RC_START_EVENT_COUNT 12

#endif
