#ifndef REDCORE_OCEAN_ITEM_NAMES_H
#define REDCORE_OCEAN_ITEM_NAMES_H

#include <stdio.h>

#define RC_ITEM_NAME_COUNT 98
static const char *const RC_ITEM_NAMES[] = {
    "",
    "MASTER BALL",
    "ULTRA BALL",
    "GREAT BALL",
    "POKe BALL",
    "TOWN MAP",
    "BICYCLE",
    "?????",
    "SAFARI BALL",
    "POKeDEX",
    "MOON STONE",
    "ANTIDOTE",
    "BURN HEAL",
    "ICE HEAL",
    "AWAKENING",
    "PARLYZ HEAL",
    "FULL RESTORE",
    "MAX POTION",
    "HYPER POTION",
    "SUPER POTION",
    "POTION",
    "BOULDERBADGE",
    "CASCADEBADGE",
    "THUNDERBADGE",
    "RAINBOWBADGE",
    "SOULBADGE",
    "MARSHBADGE",
    "VOLCANOBADGE",
    "EARTHBADGE",
    "ESCAPE ROPE",
    "REPEL",
    "OLD AMBER",
    "FIRE STONE",
    "THUNDERSTONE",
    "WATER STONE",
    "HP UP",
    "PROTEIN",
    "IRON",
    "CARBOS",
    "CALCIUM",
    "RARE CANDY",
    "DOME FOSSIL",
    "HELIX FOSSIL",
    "SECRET KEY",
    "?????",
    "BIKE VOUCHER",
    "X ACCURACY",
    "LEAF STONE",
    "CARD KEY",
    "NUGGET",
    "PP UP",
    "POKe DOLL",
    "FULL HEAL",
    "REVIVE",
    "MAX REVIVE",
    "GUARD SPEC.",
    "SUPER REPEL",
    "MAX REPEL",
    "DIRE HIT",
    "COIN",
    "FRESH WATER",
    "SODA POP",
    "LEMONADE",
    "S.S.TICKET",
    "GOLD TEETH",
    "X ATTACK",
    "X DEFEND",
    "X SPEED",
    "X SPECIAL",
    "COIN CASE",
    "OAK's PARCEL",
    "ITEMFINDER",
    "SILPH SCOPE",
    "POKe FLUTE",
    "LIFT KEY",
    "EXP.ALL",
    "OLD ROD",
    "GOOD ROD",
    "SUPER ROD",
    "PP UP",
    "ETHER",
    "MAX ETHER",
    "ELIXER",
    "MAX ELIXER",
    "B2F",
    "B1F",
    "1F",
    "2F",
    "3F",
    "4F",
    "5F",
    "6F",
    "7F",
    "8F",
    "9F",
    "10F",
    "11F",
    "B4F",
};

static inline void rc_item_name(unsigned id, char *out, unsigned cap) {
    if (id > 0 && id < RC_ITEM_NAME_COUNT) snprintf(out, cap, "%s", RC_ITEM_NAMES[id]);
    else if (id >= 0xC4 && id <= 0xC8) snprintf(out, cap, "HM%02u", id - 0xC3);
    else if (id >= 0xC9 && id <= 0xFA) snprintf(out, cap, "TM%02u", id - 0xC8);
    else snprintf(out, cap, "ITEM %u", id);
}

#endif
