#ifndef REDCORE_OCEAN_EVENTS_H
#define REDCORE_OCEAN_EVENTS_H

typedef struct RedcoreEvent {
    int bit;
    const char *name;
} RedcoreEvent;

static const RedcoreEvent REDCORE_EVENT_LIST[] = {
    {EVENT_FOLLOWED_OAK_INTO_LAB, "Followed Oak Into Lab"},
    {EVENT_HALL_OF_FAME_DEX_RATING, "Hall Of Fame Dex Rating"},
    {EVENT_PALLET_AFTER_GETTING_POKEBALLS, "Pallet After Getting Pokeballs"},
    {EVENT_GOT_TOWN_MAP, "Got Town Map"},
    {EVENT_ENTERED_BLUES_HOUSE, "Entered Blues House"},
    {EVENT_DAISY_WALKING, "Daisy Walking"},
    {EVENT_FOLLOWED_OAK_INTO_LAB_2, "Followed Oak Into Lab 2"},
    {EVENT_OAK_ASKED_TO_CHOOSE_MON, "Oak Asked To Choose Mon"},
    {EVENT_GOT_STARTER, "Got Starter"},
    {EVENT_BATTLED_RIVAL_IN_OAKS_LAB, "Battled Rival In Oaks Lab"},
    {EVENT_GOT_POKEBALLS_FROM_OAK, "Got Pokeballs From Oak"},
    {EVENT_GOT_POKEDEX, "Got Pokedex"},
    {EVENT_PALLET_AFTER_GETTING_POKEBALLS_2, "Pallet After Getting Pokeballs 2"},
    {EVENT_OAK_APPEARED_IN_PALLET, "Oak Appeared In Pallet"},
    {EVENT_VIRIDIAN_GYM_OPEN, "Viridian Gym Open"},
    {EVENT_GOT_TM42, "Got Tm42"},
    {EVENT_OAK_GOT_PARCEL, "Oak Got Parcel"},
    {EVENT_GOT_OAKS_PARCEL, "Got Oaks Parcel"},
    {EVENT_GOT_TM27, "Got Tm27"},
    {EVENT_BEAT_VIRIDIAN_GYM_GIOVANNI, "Beat Viridian Gym Giovanni"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_0, "Beat Viridian Gym Trainer 0"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_1, "Beat Viridian Gym Trainer 1"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_2, "Beat Viridian Gym Trainer 2"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_3, "Beat Viridian Gym Trainer 3"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_4, "Beat Viridian Gym Trainer 4"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_5, "Beat Viridian Gym Trainer 5"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_6, "Beat Viridian Gym Trainer 6"},
    {EVENT_BEAT_VIRIDIAN_GYM_TRAINER_7, "Beat Viridian Gym Trainer 7"},
    {EVENT_GOT_OLD_AMBER, "Got Old Amber"},
    {EVENT_BEAT_PEWTER_GYM_TRAINER_0, "Beat Pewter Gym Trainer 0"},
    {EVENT_GOT_TM34, "Got Tm34"},
    {EVENT_BEAT_BROCK, "Beat Brock"},
    {EVENT_BEAT_CERULEAN_RIVAL, "Beat Cerulean Rival"},
    {EVENT_BEAT_CERULEAN_ROCKET_THIEF, "Beat Cerulean Rocket Thief"},
    {EVENT_BEAT_CERULEAN_GYM_TRAINER_0, "Beat Cerulean Gym Trainer 0"},
    {EVENT_BEAT_CERULEAN_GYM_TRAINER_1, "Beat Cerulean Gym Trainer 1"},
    {EVENT_GOT_TM11, "Got Tm11"},
    {EVENT_BEAT_MISTY, "Beat Misty"},
    {EVENT_GOT_BICYCLE, "Got Bicycle"},
    {EVENT_POKEMON_TOWER_RIVAL_ON_LEFT, "Pokemon Tower Rival On Left"},
    {EVENT_BEAT_POKEMON_TOWER_RIVAL, "Beat Pokemon Tower Rival"},
    {EVENT_BEAT_POKEMONTOWER_3_TRAINER_0, "Beat Pokemontower 3 Trainer 0"},
    {EVENT_BEAT_POKEMONTOWER_3_TRAINER_1, "Beat Pokemontower 3 Trainer 1"},
    {EVENT_BEAT_POKEMONTOWER_3_TRAINER_2, "Beat Pokemontower 3 Trainer 2"},
    {EVENT_BEAT_POKEMONTOWER_4_TRAINER_0, "Beat Pokemontower 4 Trainer 0"},
    {EVENT_BEAT_POKEMONTOWER_4_TRAINER_1, "Beat Pokemontower 4 Trainer 1"},
    {EVENT_BEAT_POKEMONTOWER_4_TRAINER_2, "Beat Pokemontower 4 Trainer 2"},
    {EVENT_BEAT_POKEMONTOWER_5_TRAINER_0, "Beat Pokemontower 5 Trainer 0"},
    {EVENT_BEAT_POKEMONTOWER_5_TRAINER_1, "Beat Pokemontower 5 Trainer 1"},
    {EVENT_BEAT_POKEMONTOWER_5_TRAINER_2, "Beat Pokemontower 5 Trainer 2"},
    {EVENT_BEAT_POKEMONTOWER_5_TRAINER_3, "Beat Pokemontower 5 Trainer 3"},
    {EVENT_IN_PURIFIED_ZONE, "In Purified Zone"},
    {EVENT_BEAT_POKEMONTOWER_6_TRAINER_0, "Beat Pokemontower 6 Trainer 0"},
    {EVENT_BEAT_POKEMONTOWER_6_TRAINER_1, "Beat Pokemontower 6 Trainer 1"},
    {EVENT_BEAT_POKEMONTOWER_6_TRAINER_2, "Beat Pokemontower 6 Trainer 2"},
    {EVENT_BEAT_GHOST_MAROWAK, "Beat Ghost Marowak"},
    {EVENT_BEAT_POKEMONTOWER_7_TRAINER_0, "Beat Pokemontower 7 Trainer 0"},
    {EVENT_BEAT_POKEMONTOWER_7_TRAINER_1, "Beat Pokemontower 7 Trainer 1"},
    {EVENT_BEAT_POKEMONTOWER_7_TRAINER_2, "Beat Pokemontower 7 Trainer 2"},
    {EVENT_RESCUED_MR_FUJI_2, "Rescued Mr Fuji 2"},
    {EVENT_GOT_POKE_FLUTE, "Got Poke Flute"},
    {EVENT_GOT_BIKE_VOUCHER, "Got Bike Voucher"},
    {EVENT_SEEL_FAN_BOAST, "Seel Fan Boast"},
    {EVENT_PIKACHU_FAN_BOAST, "Pikachu Fan Boast"},
    {EVENT_2ND_LOCK_OPENED, "2Nd Lock Opened"},
    {EVENT_1ST_LOCK_OPENED, "1St Lock Opened"},
    {EVENT_BEAT_VERMILION_GYM_TRAINER_0, "Beat Vermilion Gym Trainer 0"},
    {EVENT_BEAT_VERMILION_GYM_TRAINER_1, "Beat Vermilion Gym Trainer 1"},
    {EVENT_BEAT_VERMILION_GYM_TRAINER_2, "Beat Vermilion Gym Trainer 2"},
    {EVENT_GOT_TM24, "Got Tm24"},
    {EVENT_BEAT_LT_SURGE, "Beat Lt Surge"},
    {EVENT_GOT_TM41, "Got Tm41"},
    {EVENT_GOT_TM13, "Got Tm13"},
    {EVENT_GOT_TM48, "Got Tm48"},
    {EVENT_GOT_TM49, "Got Tm49"},
    {EVENT_GOT_TM18, "Got Tm18"},
    {EVENT_GOT_TM21, "Got Tm21"},
    {EVENT_BEAT_ERIKA, "Beat Erika"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_0, "Beat Celadon Gym Trainer 0"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_1, "Beat Celadon Gym Trainer 1"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_2, "Beat Celadon Gym Trainer 2"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_3, "Beat Celadon Gym Trainer 3"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_4, "Beat Celadon Gym Trainer 4"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_5, "Beat Celadon Gym Trainer 5"},
    {EVENT_BEAT_CELADON_GYM_TRAINER_6, "Beat Celadon Gym Trainer 6"},
    {EVENT_FOUND_ROCKET_HIDEOUT, "Found Rocket Hideout"},
    {EVENT_GOT_10_COINS, "Got 10 Coins"},
    {EVENT_GOT_20_COINS, "Got 20 Coins"},
    {EVENT_GOT_20_COINS_2, "Got 20 Coins 2"},
    {EVENT_GOT_COIN_CASE, "Got Coin Case"},
    {EVENT_GOT_HM04, "Got Hm04"},
    {EVENT_GAVE_GOLD_TEETH, "Gave Gold Teeth"},
    {EVENT_SAFARI_GAME_OVER, "Safari Game Over"},
    {EVENT_IN_SAFARI_ZONE, "In Safari Zone"},
    {EVENT_GOT_TM06, "Got Tm06"},
    {EVENT_BEAT_KOGA, "Beat Koga"},
    {EVENT_BEAT_FUCHSIA_GYM_TRAINER_0, "Beat Fuchsia Gym Trainer 0"},
    {EVENT_BEAT_FUCHSIA_GYM_TRAINER_1, "Beat Fuchsia Gym Trainer 1"},
    {EVENT_BEAT_FUCHSIA_GYM_TRAINER_2, "Beat Fuchsia Gym Trainer 2"},
    {EVENT_BEAT_FUCHSIA_GYM_TRAINER_3, "Beat Fuchsia Gym Trainer 3"},
    {EVENT_BEAT_FUCHSIA_GYM_TRAINER_4, "Beat Fuchsia Gym Trainer 4"},
    {EVENT_BEAT_FUCHSIA_GYM_TRAINER_5, "Beat Fuchsia Gym Trainer 5"},
    {EVENT_MANSION_SWITCH_ON, "Mansion Switch On"},
    {EVENT_BEAT_MANSION_1_TRAINER_0, "Beat Mansion 1 Trainer 0"},
    {EVENT_GOT_TM38, "Got Tm38"},
    {EVENT_BEAT_BLAINE, "Beat Blaine"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_0, "Beat Cinnabar Gym Trainer 0"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_1, "Beat Cinnabar Gym Trainer 1"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_2, "Beat Cinnabar Gym Trainer 2"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_3, "Beat Cinnabar Gym Trainer 3"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_4, "Beat Cinnabar Gym Trainer 4"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_5, "Beat Cinnabar Gym Trainer 5"},
    {EVENT_BEAT_CINNABAR_GYM_TRAINER_6, "Beat Cinnabar Gym Trainer 6"},
    {EVENT_CINNABAR_GYM_GATE0_UNLOCKED, "Cinnabar Gym Gate0 Unlocked"},
    {EVENT_CINNABAR_GYM_GATE1_UNLOCKED, "Cinnabar Gym Gate1 Unlocked"},
    {EVENT_CINNABAR_GYM_GATE2_UNLOCKED, "Cinnabar Gym Gate2 Unlocked"},
    {EVENT_CINNABAR_GYM_GATE3_UNLOCKED, "Cinnabar Gym Gate3 Unlocked"},
    {EVENT_CINNABAR_GYM_GATE4_UNLOCKED, "Cinnabar Gym Gate4 Unlocked"},
    {EVENT_CINNABAR_GYM_GATE5_UNLOCKED, "Cinnabar Gym Gate5 Unlocked"},
    {EVENT_CINNABAR_GYM_GATE6_UNLOCKED, "Cinnabar Gym Gate6 Unlocked"},
    {EVENT_GOT_TM35, "Got Tm35"},
    {EVENT_GAVE_FOSSIL_TO_LAB, "Gave Fossil To Lab"},
    {EVENT_LAB_STILL_REVIVING_FOSSIL, "Lab Still Reviving Fossil"},
    {EVENT_LAB_HANDING_OVER_FOSSIL_MON, "Lab Handing Over Fossil Mon"},
    {EVENT_GOT_TM31, "Got Tm31"},
    {EVENT_DEFEATED_FIGHTING_DOJO, "Defeated Fighting Dojo"},
    {EVENT_BEAT_KARATE_MASTER, "Beat Karate Master"},
    {EVENT_BEAT_FIGHTING_DOJO_TRAINER_0, "Beat Fighting Dojo Trainer 0"},
    {EVENT_BEAT_FIGHTING_DOJO_TRAINER_1, "Beat Fighting Dojo Trainer 1"},
    {EVENT_BEAT_FIGHTING_DOJO_TRAINER_2, "Beat Fighting Dojo Trainer 2"},
    {EVENT_BEAT_FIGHTING_DOJO_TRAINER_3, "Beat Fighting Dojo Trainer 3"},
    {EVENT_GOT_HITMONLEE, "Got Hitmonlee"},
    {EVENT_GOT_HITMONCHAN, "Got Hitmonchan"},
    {EVENT_GOT_TM46, "Got Tm46"},
    {EVENT_BEAT_SABRINA, "Beat Sabrina"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_0, "Beat Saffron Gym Trainer 0"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_1, "Beat Saffron Gym Trainer 1"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_2, "Beat Saffron Gym Trainer 2"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_3, "Beat Saffron Gym Trainer 3"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_4, "Beat Saffron Gym Trainer 4"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_5, "Beat Saffron Gym Trainer 5"},
    {EVENT_BEAT_SAFFRON_GYM_TRAINER_6, "Beat Saffron Gym Trainer 6"},
    {EVENT_SILPH_CO_RECEPTIONIST_AT_DESK, "Silph Co Receptionist At Desk"},
    {EVENT_GOT_TM29, "Got Tm29"},
    {EVENT_GOT_POTION_SAMPLE, "Got Potion Sample"},
    {EVENT_GOT_HM05, "Got Hm05"},
    {EVENT_BEAT_ROUTE_3_TRAINER_0, "Beat Route 3 Trainer 0"},
    {EVENT_BEAT_ROUTE_3_TRAINER_1, "Beat Route 3 Trainer 1"},
    {EVENT_BEAT_ROUTE_3_TRAINER_2, "Beat Route 3 Trainer 2"},
    {EVENT_BEAT_ROUTE_3_TRAINER_3, "Beat Route 3 Trainer 3"},
    {EVENT_BEAT_ROUTE_3_TRAINER_4, "Beat Route 3 Trainer 4"},
    {EVENT_BEAT_ROUTE_3_TRAINER_5, "Beat Route 3 Trainer 5"},
    {EVENT_BEAT_ROUTE_3_TRAINER_6, "Beat Route 3 Trainer 6"},
    {EVENT_BEAT_ROUTE_3_TRAINER_7, "Beat Route 3 Trainer 7"},
    {EVENT_BEAT_ROUTE_4_TRAINER_0, "Beat Route 4 Trainer 0"},
    {EVENT_BOUGHT_MAGIKARP, "Bought Magikarp"},
    {EVENT_BEAT_ROUTE_6_TRAINER_0, "Beat Route 6 Trainer 0"},
    {EVENT_BEAT_ROUTE_6_TRAINER_1, "Beat Route 6 Trainer 1"},
    {EVENT_BEAT_ROUTE_6_TRAINER_2, "Beat Route 6 Trainer 2"},
    {EVENT_BEAT_ROUTE_6_TRAINER_3, "Beat Route 6 Trainer 3"},
    {EVENT_BEAT_ROUTE_6_TRAINER_4, "Beat Route 6 Trainer 4"},
    {EVENT_BEAT_ROUTE_6_TRAINER_5, "Beat Route 6 Trainer 5"},
    {EVENT_BEAT_ROUTE_8_TRAINER_0, "Beat Route 8 Trainer 0"},
    {EVENT_BEAT_ROUTE_8_TRAINER_1, "Beat Route 8 Trainer 1"},
    {EVENT_BEAT_ROUTE_8_TRAINER_2, "Beat Route 8 Trainer 2"},
    {EVENT_BEAT_ROUTE_8_TRAINER_3, "Beat Route 8 Trainer 3"},
    {EVENT_BEAT_ROUTE_8_TRAINER_4, "Beat Route 8 Trainer 4"},
    {EVENT_BEAT_ROUTE_8_TRAINER_5, "Beat Route 8 Trainer 5"},
    {EVENT_BEAT_ROUTE_8_TRAINER_6, "Beat Route 8 Trainer 6"},
    {EVENT_BEAT_ROUTE_8_TRAINER_7, "Beat Route 8 Trainer 7"},
    {EVENT_BEAT_ROUTE_8_TRAINER_8, "Beat Route 8 Trainer 8"},
    {EVENT_BEAT_ROUTE_9_TRAINER_0, "Beat Route 9 Trainer 0"},
    {EVENT_BEAT_ROUTE_9_TRAINER_1, "Beat Route 9 Trainer 1"},
    {EVENT_BEAT_ROUTE_9_TRAINER_2, "Beat Route 9 Trainer 2"},
    {EVENT_BEAT_ROUTE_9_TRAINER_3, "Beat Route 9 Trainer 3"},
    {EVENT_BEAT_ROUTE_9_TRAINER_4, "Beat Route 9 Trainer 4"},
    {EVENT_BEAT_ROUTE_9_TRAINER_5, "Beat Route 9 Trainer 5"},
    {EVENT_BEAT_ROUTE_9_TRAINER_6, "Beat Route 9 Trainer 6"},
    {EVENT_BEAT_ROUTE_9_TRAINER_7, "Beat Route 9 Trainer 7"},
    {EVENT_BEAT_ROUTE_9_TRAINER_8, "Beat Route 9 Trainer 8"},
    {EVENT_BEAT_ROUTE_10_TRAINER_0, "Beat Route 10 Trainer 0"},
    {EVENT_BEAT_ROUTE_10_TRAINER_1, "Beat Route 10 Trainer 1"},
    {EVENT_BEAT_ROUTE_10_TRAINER_2, "Beat Route 10 Trainer 2"},
    {EVENT_BEAT_ROUTE_10_TRAINER_3, "Beat Route 10 Trainer 3"},
    {EVENT_BEAT_ROUTE_10_TRAINER_4, "Beat Route 10 Trainer 4"},
    {EVENT_BEAT_ROUTE_10_TRAINER_5, "Beat Route 10 Trainer 5"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_0, "Beat Rock Tunnel 1 Trainer 0"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_1, "Beat Rock Tunnel 1 Trainer 1"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_2, "Beat Rock Tunnel 1 Trainer 2"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_3, "Beat Rock Tunnel 1 Trainer 3"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_4, "Beat Rock Tunnel 1 Trainer 4"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_5, "Beat Rock Tunnel 1 Trainer 5"},
    {EVENT_BEAT_ROCK_TUNNEL_1_TRAINER_6, "Beat Rock Tunnel 1 Trainer 6"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_0, "Beat Power Plant Voltorb 0"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_1, "Beat Power Plant Voltorb 1"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_2, "Beat Power Plant Voltorb 2"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_3, "Beat Power Plant Voltorb 3"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_4, "Beat Power Plant Voltorb 4"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_5, "Beat Power Plant Voltorb 5"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_6, "Beat Power Plant Voltorb 6"},
    {EVENT_BEAT_POWER_PLANT_VOLTORB_7, "Beat Power Plant Voltorb 7"},
    {EVENT_BEAT_ZAPDOS, "Beat Zapdos"},
    {EVENT_BEAT_ROUTE_11_TRAINER_0, "Beat Route 11 Trainer 0"},
    {EVENT_BEAT_ROUTE_11_TRAINER_1, "Beat Route 11 Trainer 1"},
    {EVENT_BEAT_ROUTE_11_TRAINER_2, "Beat Route 11 Trainer 2"},
    {EVENT_BEAT_ROUTE_11_TRAINER_3, "Beat Route 11 Trainer 3"},
    {EVENT_BEAT_ROUTE_11_TRAINER_4, "Beat Route 11 Trainer 4"},
    {EVENT_BEAT_ROUTE_11_TRAINER_5, "Beat Route 11 Trainer 5"},
    {EVENT_BEAT_ROUTE_11_TRAINER_6, "Beat Route 11 Trainer 6"},
    {EVENT_BEAT_ROUTE_11_TRAINER_7, "Beat Route 11 Trainer 7"},
    {EVENT_BEAT_ROUTE_11_TRAINER_8, "Beat Route 11 Trainer 8"},
    {EVENT_BEAT_ROUTE_11_TRAINER_9, "Beat Route 11 Trainer 9"},
    {EVENT_GOT_ITEMFINDER, "Got Itemfinder"},
    {EVENT_GOT_TM39, "Got Tm39"},
    {EVENT_BEAT_ROUTE_12_TRAINER_0, "Beat Route 12 Trainer 0"},
    {EVENT_BEAT_ROUTE_12_TRAINER_1, "Beat Route 12 Trainer 1"},
    {EVENT_BEAT_ROUTE_12_TRAINER_2, "Beat Route 12 Trainer 2"},
    {EVENT_BEAT_ROUTE_12_TRAINER_3, "Beat Route 12 Trainer 3"},
    {EVENT_BEAT_ROUTE_12_TRAINER_4, "Beat Route 12 Trainer 4"},
    {EVENT_BEAT_ROUTE_12_TRAINER_5, "Beat Route 12 Trainer 5"},
    {EVENT_BEAT_ROUTE_12_TRAINER_6, "Beat Route 12 Trainer 6"},
    {EVENT_FIGHT_ROUTE12_SNORLAX, "Fight Route12 Snorlax"},
    {EVENT_BEAT_ROUTE12_SNORLAX, "Beat Route12 Snorlax"},
    {EVENT_BEAT_ROUTE_13_TRAINER_0, "Beat Route 13 Trainer 0"},
    {EVENT_BEAT_ROUTE_13_TRAINER_1, "Beat Route 13 Trainer 1"},
    {EVENT_BEAT_ROUTE_13_TRAINER_2, "Beat Route 13 Trainer 2"},
    {EVENT_BEAT_ROUTE_13_TRAINER_3, "Beat Route 13 Trainer 3"},
    {EVENT_BEAT_ROUTE_13_TRAINER_4, "Beat Route 13 Trainer 4"},
    {EVENT_BEAT_ROUTE_13_TRAINER_5, "Beat Route 13 Trainer 5"},
    {EVENT_BEAT_ROUTE_13_TRAINER_6, "Beat Route 13 Trainer 6"},
    {EVENT_BEAT_ROUTE_13_TRAINER_7, "Beat Route 13 Trainer 7"},
    {EVENT_BEAT_ROUTE_13_TRAINER_8, "Beat Route 13 Trainer 8"},
    {EVENT_BEAT_ROUTE_13_TRAINER_9, "Beat Route 13 Trainer 9"},
    {EVENT_BEAT_ROUTE_14_TRAINER_0, "Beat Route 14 Trainer 0"},
    {EVENT_BEAT_ROUTE_14_TRAINER_1, "Beat Route 14 Trainer 1"},
    {EVENT_BEAT_ROUTE_14_TRAINER_2, "Beat Route 14 Trainer 2"},
    {EVENT_BEAT_ROUTE_14_TRAINER_3, "Beat Route 14 Trainer 3"},
    {EVENT_BEAT_ROUTE_14_TRAINER_4, "Beat Route 14 Trainer 4"},
    {EVENT_BEAT_ROUTE_14_TRAINER_5, "Beat Route 14 Trainer 5"},
    {EVENT_BEAT_ROUTE_14_TRAINER_6, "Beat Route 14 Trainer 6"},
    {EVENT_BEAT_ROUTE_14_TRAINER_7, "Beat Route 14 Trainer 7"},
    {EVENT_BEAT_ROUTE_14_TRAINER_8, "Beat Route 14 Trainer 8"},
    {EVENT_BEAT_ROUTE_14_TRAINER_9, "Beat Route 14 Trainer 9"},
    {EVENT_GOT_EXP_ALL, "Got Exp All"},
    {EVENT_BEAT_ROUTE_15_TRAINER_0, "Beat Route 15 Trainer 0"},
    {EVENT_BEAT_ROUTE_15_TRAINER_1, "Beat Route 15 Trainer 1"},
    {EVENT_BEAT_ROUTE_15_TRAINER_2, "Beat Route 15 Trainer 2"},
    {EVENT_BEAT_ROUTE_15_TRAINER_3, "Beat Route 15 Trainer 3"},
    {EVENT_BEAT_ROUTE_15_TRAINER_4, "Beat Route 15 Trainer 4"},
    {EVENT_BEAT_ROUTE_15_TRAINER_5, "Beat Route 15 Trainer 5"},
    {EVENT_BEAT_ROUTE_15_TRAINER_6, "Beat Route 15 Trainer 6"},
    {EVENT_BEAT_ROUTE_15_TRAINER_7, "Beat Route 15 Trainer 7"},
    {EVENT_BEAT_ROUTE_15_TRAINER_8, "Beat Route 15 Trainer 8"},
    {EVENT_BEAT_ROUTE_15_TRAINER_9, "Beat Route 15 Trainer 9"},
    {EVENT_BEAT_ROUTE_16_TRAINER_0, "Beat Route 16 Trainer 0"},
    {EVENT_BEAT_ROUTE_16_TRAINER_1, "Beat Route 16 Trainer 1"},
    {EVENT_BEAT_ROUTE_16_TRAINER_2, "Beat Route 16 Trainer 2"},
    {EVENT_BEAT_ROUTE_16_TRAINER_3, "Beat Route 16 Trainer 3"},
    {EVENT_BEAT_ROUTE_16_TRAINER_4, "Beat Route 16 Trainer 4"},
    {EVENT_BEAT_ROUTE_16_TRAINER_5, "Beat Route 16 Trainer 5"},
    {EVENT_FIGHT_ROUTE16_SNORLAX, "Fight Route16 Snorlax"},
    {EVENT_BEAT_ROUTE16_SNORLAX, "Beat Route16 Snorlax"},
    {EVENT_GOT_HM02, "Got Hm02"},
    {EVENT_RESCUED_MR_FUJI, "Rescued Mr Fuji"},
    {EVENT_BEAT_ROUTE_17_TRAINER_0, "Beat Route 17 Trainer 0"},
    {EVENT_BEAT_ROUTE_17_TRAINER_1, "Beat Route 17 Trainer 1"},
    {EVENT_BEAT_ROUTE_17_TRAINER_2, "Beat Route 17 Trainer 2"},
    {EVENT_BEAT_ROUTE_17_TRAINER_3, "Beat Route 17 Trainer 3"},
    {EVENT_BEAT_ROUTE_17_TRAINER_4, "Beat Route 17 Trainer 4"},
    {EVENT_BEAT_ROUTE_17_TRAINER_5, "Beat Route 17 Trainer 5"},
    {EVENT_BEAT_ROUTE_17_TRAINER_6, "Beat Route 17 Trainer 6"},
    {EVENT_BEAT_ROUTE_17_TRAINER_7, "Beat Route 17 Trainer 7"},
    {EVENT_BEAT_ROUTE_17_TRAINER_8, "Beat Route 17 Trainer 8"},
    {EVENT_BEAT_ROUTE_17_TRAINER_9, "Beat Route 17 Trainer 9"},
    {EVENT_BEAT_ROUTE_18_TRAINER_0, "Beat Route 18 Trainer 0"},
    {EVENT_BEAT_ROUTE_18_TRAINER_1, "Beat Route 18 Trainer 1"},
    {EVENT_BEAT_ROUTE_18_TRAINER_2, "Beat Route 18 Trainer 2"},
    {EVENT_BEAT_ROUTE_19_TRAINER_0, "Beat Route 19 Trainer 0"},
    {EVENT_BEAT_ROUTE_19_TRAINER_1, "Beat Route 19 Trainer 1"},
    {EVENT_BEAT_ROUTE_19_TRAINER_2, "Beat Route 19 Trainer 2"},
    {EVENT_BEAT_ROUTE_19_TRAINER_3, "Beat Route 19 Trainer 3"},
    {EVENT_BEAT_ROUTE_19_TRAINER_4, "Beat Route 19 Trainer 4"},
    {EVENT_BEAT_ROUTE_19_TRAINER_5, "Beat Route 19 Trainer 5"},
    {EVENT_BEAT_ROUTE_19_TRAINER_6, "Beat Route 19 Trainer 6"},
    {EVENT_BEAT_ROUTE_19_TRAINER_7, "Beat Route 19 Trainer 7"},
    {EVENT_BEAT_ROUTE_19_TRAINER_8, "Beat Route 19 Trainer 8"},
    {EVENT_BEAT_ROUTE_19_TRAINER_9, "Beat Route 19 Trainer 9"},
    {EVENT_IN_SEAFOAM_ISLANDS, "In Seafoam Islands"},
    {EVENT_BEAT_ROUTE_20_TRAINER_0, "Beat Route 20 Trainer 0"},
    {EVENT_BEAT_ROUTE_20_TRAINER_1, "Beat Route 20 Trainer 1"},
    {EVENT_BEAT_ROUTE_20_TRAINER_2, "Beat Route 20 Trainer 2"},
    {EVENT_BEAT_ROUTE_20_TRAINER_3, "Beat Route 20 Trainer 3"},
    {EVENT_BEAT_ROUTE_20_TRAINER_4, "Beat Route 20 Trainer 4"},
    {EVENT_BEAT_ROUTE_20_TRAINER_5, "Beat Route 20 Trainer 5"},
    {EVENT_BEAT_ROUTE_20_TRAINER_6, "Beat Route 20 Trainer 6"},
    {EVENT_BEAT_ROUTE_20_TRAINER_7, "Beat Route 20 Trainer 7"},
    {EVENT_BEAT_ROUTE_20_TRAINER_8, "Beat Route 20 Trainer 8"},
    {EVENT_BEAT_ROUTE_20_TRAINER_9, "Beat Route 20 Trainer 9"},
    {EVENT_SEAFOAM1_BOULDER1_DOWN_HOLE, "Seafoam1 Boulder1 Down Hole"},
    {EVENT_SEAFOAM1_BOULDER2_DOWN_HOLE, "Seafoam1 Boulder2 Down Hole"},
    {EVENT_BEAT_ROUTE_21_TRAINER_0, "Beat Route 21 Trainer 0"},
    {EVENT_BEAT_ROUTE_21_TRAINER_1, "Beat Route 21 Trainer 1"},
    {EVENT_BEAT_ROUTE_21_TRAINER_2, "Beat Route 21 Trainer 2"},
    {EVENT_BEAT_ROUTE_21_TRAINER_3, "Beat Route 21 Trainer 3"},
    {EVENT_BEAT_ROUTE_21_TRAINER_4, "Beat Route 21 Trainer 4"},
    {EVENT_BEAT_ROUTE_21_TRAINER_5, "Beat Route 21 Trainer 5"},
    {EVENT_BEAT_ROUTE_21_TRAINER_6, "Beat Route 21 Trainer 6"},
    {EVENT_BEAT_ROUTE_21_TRAINER_7, "Beat Route 21 Trainer 7"},
    {EVENT_BEAT_ROUTE_21_TRAINER_8, "Beat Route 21 Trainer 8"},
    {EVENT_1ST_ROUTE22_RIVAL_BATTLE, "1St Route22 Rival Battle"},
    {EVENT_2ND_ROUTE22_RIVAL_BATTLE, "2Nd Route22 Rival Battle"},
    {EVENT_BEAT_ROUTE22_RIVAL_1ST_BATTLE, "Beat Route22 Rival 1St Battle"},
    {EVENT_BEAT_ROUTE22_RIVAL_2ND_BATTLE, "Beat Route22 Rival 2Nd Battle"},
    {EVENT_ROUTE22_RIVAL_WANTS_BATTLE, "Route22 Rival Wants Battle"},
    {EVENT_PASSED_CASCADEBADGE_CHECK, "Passed Cascadebadge Check"},
    {EVENT_PASSED_THUNDERBADGE_CHECK, "Passed Thunderbadge Check"},
    {EVENT_PASSED_RAINBOWBADGE_CHECK, "Passed Rainbowbadge Check"},
    {EVENT_PASSED_SOULBADGE_CHECK, "Passed Soulbadge Check"},
    {EVENT_PASSED_MARSHBADGE_CHECK, "Passed Marshbadge Check"},
    {EVENT_PASSED_VOLCANOBADGE_CHECK, "Passed Volcanobadge Check"},
    {EVENT_PASSED_EARTHBADGE_CHECK, "Passed Earthbadge Check"},
    {EVENT_VICTORY_ROAD_2_BOULDER_ON_SWITCH1, "Victory Road 2 Boulder On Switch1"},
    {EVENT_BEAT_VICTORY_ROAD_2_TRAINER_0, "Beat Victory Road 2 Trainer 0"},
    {EVENT_BEAT_VICTORY_ROAD_2_TRAINER_1, "Beat Victory Road 2 Trainer 1"},
    {EVENT_BEAT_VICTORY_ROAD_2_TRAINER_2, "Beat Victory Road 2 Trainer 2"},
    {EVENT_BEAT_VICTORY_ROAD_2_TRAINER_3, "Beat Victory Road 2 Trainer 3"},
    {EVENT_BEAT_VICTORY_ROAD_2_TRAINER_4, "Beat Victory Road 2 Trainer 4"},
    {EVENT_BEAT_MOLTRES, "Beat Moltres"},
    {EVENT_VICTORY_ROAD_2_BOULDER_ON_SWITCH2, "Victory Road 2 Boulder On Switch2"},
    {EVENT_GOT_NUGGET, "Got Nugget"},
    {EVENT_BEAT_ROUTE24_ROCKET, "Beat Route24 Rocket"},
    {EVENT_BEAT_ROUTE_24_TRAINER_0, "Beat Route 24 Trainer 0"},
    {EVENT_BEAT_ROUTE_24_TRAINER_1, "Beat Route 24 Trainer 1"},
    {EVENT_BEAT_ROUTE_24_TRAINER_2, "Beat Route 24 Trainer 2"},
    {EVENT_BEAT_ROUTE_24_TRAINER_3, "Beat Route 24 Trainer 3"},
    {EVENT_BEAT_ROUTE_24_TRAINER_4, "Beat Route 24 Trainer 4"},
    {EVENT_BEAT_ROUTE_24_TRAINER_5, "Beat Route 24 Trainer 5"},
    {EVENT_NUGGET_REWARD_AVAILABLE, "Nugget Reward Available"},
    {EVENT_MET_BILL, "Met Bill"},
    {EVENT_BEAT_ROUTE_25_TRAINER_0, "Beat Route 25 Trainer 0"},
    {EVENT_BEAT_ROUTE_25_TRAINER_1, "Beat Route 25 Trainer 1"},
    {EVENT_BEAT_ROUTE_25_TRAINER_2, "Beat Route 25 Trainer 2"},
    {EVENT_BEAT_ROUTE_25_TRAINER_3, "Beat Route 25 Trainer 3"},
    {EVENT_BEAT_ROUTE_25_TRAINER_4, "Beat Route 25 Trainer 4"},
    {EVENT_BEAT_ROUTE_25_TRAINER_5, "Beat Route 25 Trainer 5"},
    {EVENT_BEAT_ROUTE_25_TRAINER_6, "Beat Route 25 Trainer 6"},
    {EVENT_BEAT_ROUTE_25_TRAINER_7, "Beat Route 25 Trainer 7"},
    {EVENT_BEAT_ROUTE_25_TRAINER_8, "Beat Route 25 Trainer 8"},
    {EVENT_USED_CELL_SEPARATOR_ON_BILL, "Used Cell Separator On Bill"},
    {EVENT_GOT_SS_TICKET, "Got Ss Ticket"},
    {EVENT_MET_BILL_2, "Met Bill 2"},
    {EVENT_BILL_SAID_USE_CELL_SEPARATOR, "Bill Said Use Cell Separator"},
    {EVENT_LEFT_BILLS_HOUSE_AFTER_HELPING, "Left Bills House After Helping"},
    {EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_0, "Beat Viridian Forest Trainer 0"},
    {EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_1, "Beat Viridian Forest Trainer 1"},
    {EVENT_BEAT_VIRIDIAN_FOREST_TRAINER_2, "Beat Viridian Forest Trainer 2"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_0, "Beat Mt Moon 1 Trainer 0"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_1, "Beat Mt Moon 1 Trainer 1"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_2, "Beat Mt Moon 1 Trainer 2"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_3, "Beat Mt Moon 1 Trainer 3"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_4, "Beat Mt Moon 1 Trainer 4"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_5, "Beat Mt Moon 1 Trainer 5"},
    {EVENT_BEAT_MT_MOON_1_TRAINER_6, "Beat Mt Moon 1 Trainer 6"},
    {EVENT_BEAT_MT_MOON_EXIT_SUPER_NERD, "Beat Mt Moon Exit Super Nerd"},
    {EVENT_BEAT_MT_MOON_3_TRAINER_0, "Beat Mt Moon 3 Trainer 0"},
    {EVENT_BEAT_MT_MOON_3_TRAINER_1, "Beat Mt Moon 3 Trainer 1"},
    {EVENT_BEAT_MT_MOON_3_TRAINER_2, "Beat Mt Moon 3 Trainer 2"},
    {EVENT_BEAT_MT_MOON_3_TRAINER_3, "Beat Mt Moon 3 Trainer 3"},
    {EVENT_GOT_DOME_FOSSIL, "Got Dome Fossil"},
    {EVENT_GOT_HELIX_FOSSIL, "Got Helix Fossil"},
    {EVENT_BEAT_SS_ANNE_5_TRAINER_0, "Beat Ss Anne 5 Trainer 0"},
    {EVENT_BEAT_SS_ANNE_5_TRAINER_1, "Beat Ss Anne 5 Trainer 1"},
    {EVENT_GOT_HM01, "Got Hm01"},
    {EVENT_RUBBED_CAPTAINS_BACK, "Rubbed Captains Back"},
    {EVENT_SS_ANNE_LEFT, "Ss Anne Left"},
    {EVENT_WALKED_PAST_GUARD_AFTER_SS_ANNE_LEFT, "Walked Past Guard After Ss Anne Left"},
    {EVENT_STARTED_WALKING_OUT_OF_DOCK, "Started Walking Out Of Dock"},
    {EVENT_WALKED_OUT_OF_DOCK, "Walked Out Of Dock"},
    {EVENT_BEAT_SS_ANNE_8_TRAINER_0, "Beat Ss Anne 8 Trainer 0"},
    {EVENT_BEAT_SS_ANNE_8_TRAINER_1, "Beat Ss Anne 8 Trainer 1"},
    {EVENT_BEAT_SS_ANNE_8_TRAINER_2, "Beat Ss Anne 8 Trainer 2"},
    {EVENT_BEAT_SS_ANNE_8_TRAINER_3, "Beat Ss Anne 8 Trainer 3"},
    {EVENT_BEAT_SS_ANNE_9_TRAINER_0, "Beat Ss Anne 9 Trainer 0"},
    {EVENT_BEAT_SS_ANNE_9_TRAINER_1, "Beat Ss Anne 9 Trainer 1"},
    {EVENT_BEAT_SS_ANNE_9_TRAINER_2, "Beat Ss Anne 9 Trainer 2"},
    {EVENT_BEAT_SS_ANNE_9_TRAINER_3, "Beat Ss Anne 9 Trainer 3"},
    {EVENT_BEAT_SS_ANNE_10_TRAINER_0, "Beat Ss Anne 10 Trainer 0"},
    {EVENT_BEAT_SS_ANNE_10_TRAINER_1, "Beat Ss Anne 10 Trainer 1"},
    {EVENT_BEAT_SS_ANNE_10_TRAINER_2, "Beat Ss Anne 10 Trainer 2"},
    {EVENT_BEAT_SS_ANNE_10_TRAINER_3, "Beat Ss Anne 10 Trainer 3"},
    {EVENT_BEAT_SS_ANNE_10_TRAINER_4, "Beat Ss Anne 10 Trainer 4"},
    {EVENT_BEAT_SS_ANNE_10_TRAINER_5, "Beat Ss Anne 10 Trainer 5"},
    {EVENT_VICTORY_ROAD_3_BOULDER_ON_SWITCH1, "Victory Road 3 Boulder On Switch1"},
    {EVENT_BEAT_VICTORY_ROAD_3_TRAINER_0, "Beat Victory Road 3 Trainer 0"},
    {EVENT_BEAT_VICTORY_ROAD_3_TRAINER_1, "Beat Victory Road 3 Trainer 1"},
    {EVENT_BEAT_VICTORY_ROAD_3_TRAINER_2, "Beat Victory Road 3 Trainer 2"},
    {EVENT_BEAT_VICTORY_ROAD_3_TRAINER_3, "Beat Victory Road 3 Trainer 3"},
    {EVENT_VICTORY_ROAD_3_BOULDER_ON_SWITCH2, "Victory Road 3 Boulder On Switch2"},
    {EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_0, "Beat Rocket Hideout 1 Trainer 0"},
    {EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_1, "Beat Rocket Hideout 1 Trainer 1"},
    {EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_2, "Beat Rocket Hideout 1 Trainer 2"},
    {EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_3, "Beat Rocket Hideout 1 Trainer 3"},
    {EVENT_BEAT_ROCKET_HIDEOUT_1_TRAINER_4, "Beat Rocket Hideout 1 Trainer 4"},
    {EVENT_BEAT_ROCKET_HIDEOUT_2_TRAINER_0, "Beat Rocket Hideout 2 Trainer 0"},
    {EVENT_BEAT_ROCKET_HIDEOUT_3_TRAINER_0, "Beat Rocket Hideout 3 Trainer 0"},
    {EVENT_BEAT_ROCKET_HIDEOUT_3_TRAINER_1, "Beat Rocket Hideout 3 Trainer 1"},
    {EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_0, "Beat Rocket Hideout 4 Trainer 0"},
    {EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_1, "Beat Rocket Hideout 4 Trainer 1"},
    {EVENT_BEAT_ROCKET_HIDEOUT_4_TRAINER_2, "Beat Rocket Hideout 4 Trainer 2"},
    {EVENT_ROCKET_HIDEOUT_4_DOOR_UNLOCKED, "Rocket Hideout 4 Door Unlocked"},
    {EVENT_ROCKET_DROPPED_LIFT_KEY, "Rocket Dropped Lift Key"},
    {EVENT_BEAT_ROCKET_HIDEOUT_GIOVANNI, "Beat Rocket Hideout Giovanni"},
    {EVENT_BEAT_SILPH_CO_2F_TRAINER_0, "Beat Silph Co 2F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_2F_TRAINER_1, "Beat Silph Co 2F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_2F_TRAINER_2, "Beat Silph Co 2F Trainer 2"},
    {EVENT_BEAT_SILPH_CO_2F_TRAINER_3, "Beat Silph Co 2F Trainer 3"},
    {EVENT_SILPH_CO_2_UNLOCKED_DOOR1, "Silph Co 2 Unlocked Door1"},
    {EVENT_SILPH_CO_2_UNLOCKED_DOOR2, "Silph Co 2 Unlocked Door2"},
    {EVENT_GOT_TM36, "Got Tm36"},
    {EVENT_BEAT_SILPH_CO_3F_TRAINER_0, "Beat Silph Co 3F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_3F_TRAINER_1, "Beat Silph Co 3F Trainer 1"},
    {EVENT_SILPH_CO_3_UNLOCKED_DOOR1, "Silph Co 3 Unlocked Door1"},
    {EVENT_SILPH_CO_3_UNLOCKED_DOOR2, "Silph Co 3 Unlocked Door2"},
    {EVENT_BEAT_SILPH_CO_4F_TRAINER_0, "Beat Silph Co 4F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_4F_TRAINER_1, "Beat Silph Co 4F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_4F_TRAINER_2, "Beat Silph Co 4F Trainer 2"},
    {EVENT_SILPH_CO_4_UNLOCKED_DOOR1, "Silph Co 4 Unlocked Door1"},
    {EVENT_SILPH_CO_4_UNLOCKED_DOOR2, "Silph Co 4 Unlocked Door2"},
    {EVENT_BEAT_SILPH_CO_5F_TRAINER_0, "Beat Silph Co 5F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_5F_TRAINER_1, "Beat Silph Co 5F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_5F_TRAINER_2, "Beat Silph Co 5F Trainer 2"},
    {EVENT_BEAT_SILPH_CO_5F_TRAINER_3, "Beat Silph Co 5F Trainer 3"},
    {EVENT_SILPH_CO_5_UNLOCKED_DOOR1, "Silph Co 5 Unlocked Door1"},
    {EVENT_SILPH_CO_5_UNLOCKED_DOOR2, "Silph Co 5 Unlocked Door2"},
    {EVENT_SILPH_CO_5_UNLOCKED_DOOR3, "Silph Co 5 Unlocked Door3"},
    {EVENT_BEAT_SILPH_CO_6F_TRAINER_0, "Beat Silph Co 6F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_6F_TRAINER_1, "Beat Silph Co 6F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_6F_TRAINER_2, "Beat Silph Co 6F Trainer 2"},
    {EVENT_SILPH_CO_6_UNLOCKED_DOOR, "Silph Co 6 Unlocked Door"},
    {EVENT_BEAT_SILPH_CO_RIVAL, "Beat Silph Co Rival"},
    {EVENT_BEAT_SILPH_CO_7F_TRAINER_0, "Beat Silph Co 7F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_7F_TRAINER_1, "Beat Silph Co 7F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_7F_TRAINER_2, "Beat Silph Co 7F Trainer 2"},
    {EVENT_BEAT_SILPH_CO_7F_TRAINER_3, "Beat Silph Co 7F Trainer 3"},
    {EVENT_SILPH_CO_7_UNLOCKED_DOOR1, "Silph Co 7 Unlocked Door1"},
    {EVENT_SILPH_CO_7_UNLOCKED_DOOR2, "Silph Co 7 Unlocked Door2"},
    {EVENT_SILPH_CO_7_UNLOCKED_DOOR3, "Silph Co 7 Unlocked Door3"},
    {EVENT_BEAT_SILPH_CO_8F_TRAINER_0, "Beat Silph Co 8F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_8F_TRAINER_1, "Beat Silph Co 8F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_8F_TRAINER_2, "Beat Silph Co 8F Trainer 2"},
    {EVENT_SILPH_CO_8_UNLOCKED_DOOR, "Silph Co 8 Unlocked Door"},
    {EVENT_BEAT_SILPH_CO_9F_TRAINER_0, "Beat Silph Co 9F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_9F_TRAINER_1, "Beat Silph Co 9F Trainer 1"},
    {EVENT_BEAT_SILPH_CO_9F_TRAINER_2, "Beat Silph Co 9F Trainer 2"},
    {EVENT_SILPH_CO_9_UNLOCKED_DOOR1, "Silph Co 9 Unlocked Door1"},
    {EVENT_SILPH_CO_9_UNLOCKED_DOOR2, "Silph Co 9 Unlocked Door2"},
    {EVENT_SILPH_CO_9_UNLOCKED_DOOR3, "Silph Co 9 Unlocked Door3"},
    {EVENT_SILPH_CO_9_UNLOCKED_DOOR4, "Silph Co 9 Unlocked Door4"},
    {EVENT_BEAT_SILPH_CO_10F_TRAINER_0, "Beat Silph Co 10F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_10F_TRAINER_1, "Beat Silph Co 10F Trainer 1"},
    {EVENT_SILPH_CO_10_UNLOCKED_DOOR, "Silph Co 10 Unlocked Door"},
    {EVENT_BEAT_SILPH_CO_11F_TRAINER_0, "Beat Silph Co 11F Trainer 0"},
    {EVENT_BEAT_SILPH_CO_11F_TRAINER_1, "Beat Silph Co 11F Trainer 1"},
    {EVENT_SILPH_CO_11_UNLOCKED_DOOR, "Silph Co 11 Unlocked Door"},
    {EVENT_GOT_MASTER_BALL, "Got Master Ball"},
    {EVENT_BEAT_SILPH_CO_GIOVANNI, "Beat Silph Co Giovanni"},
    {EVENT_BEAT_MANSION_2_TRAINER_0, "Beat Mansion 2 Trainer 0"},
    {EVENT_BEAT_MANSION_3_TRAINER_0, "Beat Mansion 3 Trainer 0"},
    {EVENT_BEAT_MANSION_3_TRAINER_1, "Beat Mansion 3 Trainer 1"},
    {EVENT_BEAT_MANSION_4_TRAINER_0, "Beat Mansion 4 Trainer 0"},
    {EVENT_BEAT_MANSION_4_TRAINER_1, "Beat Mansion 4 Trainer 1"},
    {EVENT_GOT_HM03, "Got Hm03"},
    {EVENT_BEAT_MEWTWO, "Beat Mewtwo"},
    {EVENT_BEAT_LORELEIS_ROOM_TRAINER_0, "Beat Loreleis Room Trainer 0"},
    {EVENT_AUTOWALKED_INTO_LORELEIS_ROOM, "Autowalked Into Loreleis Room"},
    {EVENT_BEAT_BRUNOS_ROOM_TRAINER_0, "Beat Brunos Room Trainer 0"},
    {EVENT_AUTOWALKED_INTO_BRUNOS_ROOM, "Autowalked Into Brunos Room"},
    {EVENT_BEAT_AGATHAS_ROOM_TRAINER_0, "Beat Agathas Room Trainer 0"},
    {EVENT_AUTOWALKED_INTO_AGATHAS_ROOM, "Autowalked Into Agathas Room"},
    {EVENT_BEAT_LANCES_ROOM_TRAINER_0, "Beat Lances Room Trainer 0"},
    {EVENT_BEAT_LANCE, "Beat Lance"},
    {EVENT_LANCES_ROOM_LOCK_DOOR, "Lances Room Lock Door"},
    {EVENT_BEAT_CHAMPION_RIVAL, "Beat Champion Rival"},
    {EVENT_BEAT_VICTORY_ROAD_1_TRAINER_0, "Beat Victory Road 1 Trainer 0"},
    {EVENT_BEAT_VICTORY_ROAD_1_TRAINER_1, "Beat Victory Road 1 Trainer 1"},
    {EVENT_VICTORY_ROAD_1_BOULDER_ON_SWITCH, "Victory Road 1 Boulder On Switch"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_0, "Beat Rock Tunnel 2 Trainer 0"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_1, "Beat Rock Tunnel 2 Trainer 1"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_2, "Beat Rock Tunnel 2 Trainer 2"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_3, "Beat Rock Tunnel 2 Trainer 3"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_4, "Beat Rock Tunnel 2 Trainer 4"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_5, "Beat Rock Tunnel 2 Trainer 5"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_6, "Beat Rock Tunnel 2 Trainer 6"},
    {EVENT_BEAT_ROCK_TUNNEL_2_TRAINER_7, "Beat Rock Tunnel 2 Trainer 7"},
    {EVENT_SEAFOAM2_BOULDER1_DOWN_HOLE, "Seafoam2 Boulder1 Down Hole"},
    {EVENT_SEAFOAM2_BOULDER2_DOWN_HOLE, "Seafoam2 Boulder2 Down Hole"},
    {EVENT_SEAFOAM3_BOULDER1_DOWN_HOLE, "Seafoam3 Boulder1 Down Hole"},
    {EVENT_SEAFOAM3_BOULDER2_DOWN_HOLE, "Seafoam3 Boulder2 Down Hole"},
    {EVENT_SEAFOAM4_BOULDER1_DOWN_HOLE, "Seafoam4 Boulder1 Down Hole"},
    {EVENT_SEAFOAM4_BOULDER2_DOWN_HOLE, "Seafoam4 Boulder2 Down Hole"},
    {EVENT_BEAT_ARTICUNO, "Beat Articuno"},
};
#define REDCORE_EVENT_COUNT (sizeof(REDCORE_EVENT_LIST) / sizeof(REDCORE_EVENT_LIST[0]))

#endif
