#ifndef POKERED_LAYOUT_H
#define POKERED_LAYOUT_H

#define SCREEN_WIDTH 160
#define SCALED_WIDTH 80
#define SCALED_HEIGHT 72
#define SCALED_PIXELS (SCALED_WIDTH * SCALED_HEIGHT)

#define PARTY_SIZE 6
#define MON_FIELDS 3     // species, level, hp fraction (current_hp / max_hp)
#define PARTY_OBS (PARTY_SIZE * MON_FIELDS)

// battle_type, then the player's and the opponent's active mon (MON_FIELDS each).
#define BATTLE_TYPE_NONE 0
#define BATTLE_TYPE_WILD 1
#define BATTLE_TYPE_TRAINER 2
#define BATTLE_TYPE_COUNT 3
#define BATTLE_OBS (1 + 2 * MON_FIELDS)
#define BATTLE_PLAYER_MON_OFFSET 1
#define BATTLE_ENEMY_MON_OFFSET (1 + MON_FIELDS)

#define BAG_SLOTS 20     // bag capacity; each slot is (item id, quantity), empty = 0, 0
#define BAG_FIELDS 2
#define BAG_OBS (BAG_SLOTS * BAG_FIELDS)

#define BLOCK_PIXELS 16
#define BLOCKS_WIDE (SCREEN_WIDTH / BLOCK_PIXELS)
#define BLOCKS_TALL (144 / BLOCK_PIXELS)
#define PLAYER_BLOCK_COL 4
#define PLAYER_BLOCK_ROW 4

#define VISITED_MASK_OBS (BLOCKS_WIDE * BLOCKS_TALL)

#define TOTAL_OBSERVATIONS (SCALED_PIXELS + VISITED_MASK_OBS + BATTLE_OBS + PARTY_OBS + BAG_OBS)
#define VISITED_MASK_OFFSET SCALED_PIXELS
#define BATTLE_OBS_OFFSET (VISITED_MASK_OFFSET + VISITED_MASK_OBS)
#define PARTY_OBS_OFFSET (BATTLE_OBS_OFFSET + BATTLE_OBS)
#define BAG_OBS_OFFSET (PARTY_OBS_OFFSET + PARTY_OBS)

typedef enum {
    PKRED_ACTION_A = 0,
    PKRED_ACTION_B,
    PKRED_ACTION_RIGHT,
    PKRED_ACTION_LEFT,
    PKRED_ACTION_UP,
    PKRED_ACTION_DOWN,
    PKRED_ACTION_COUNT
} PokeredAction;

#endif
