#ifndef POKERED_LAYOUT_H
#define POKERED_LAYOUT_H

#define SCREEN_WIDTH 160
#define SCALED_WIDTH 160
#define SCALED_HEIGHT 144
#define SCALED_PIXELS (SCALED_WIDTH * SCALED_HEIGHT)

#define PARTY_SIZE 6
#define PARTY_FIELDS 8
#define PARTY_OBS (PARTY_SIZE * PARTY_FIELDS)

#define BATTLE_OBS 4

#define POSITION_SCALAR_OBS 5

#define PROGRESS_OBS 3

#define PKRED_LAYOUT_NUM_BADGES 8
#define PKRED_LAYOUT_BAG_TRACKED_ITEMS 23
#define PKRED_LAYOUT_KEY_ITEMS 16

#define BLOCK_PIXELS 16
#define BLOCKS_WIDE (SCREEN_WIDTH / BLOCK_PIXELS)
#define BLOCKS_TALL (144 / BLOCK_PIXELS)
#define PLAYER_BLOCK_COL 4
#define PLAYER_BLOCK_ROW 4

#define VISITED_MASK_OBS (BLOCKS_WIDE * BLOCKS_TALL)

#define TOTAL_OBSERVATIONS (SCALED_PIXELS + VISITED_MASK_OBS + BATTLE_OBS + \
    POSITION_SCALAR_OBS + PROGRESS_OBS + PARTY_OBS)
#define VISITED_MASK_OFFSET SCALED_PIXELS
#define BATTLE_OBS_OFFSET (VISITED_MASK_OFFSET + VISITED_MASK_OBS)
#define POSITION_OBS_OFFSET (BATTLE_OBS_OFFSET + BATTLE_OBS)
#define PROGRESS_OBS_OFFSET (POSITION_OBS_OFFSET + POSITION_SCALAR_OBS)
#define PARTY_OBS_OFFSET (PROGRESS_OBS_OFFSET + PROGRESS_OBS)

typedef enum {
    PKRED_ACTION_A = 0,
    PKRED_ACTION_B,
    PKRED_ACTION_RIGHT,
    PKRED_ACTION_LEFT,
    PKRED_ACTION_UP,
    PKRED_ACTION_DOWN,
    PKRED_ACTION_COUNT
} PokeredAction;

#endif
