#ifndef POKERED_LAYOUT_H
#define POKERED_LAYOUT_H

#define SCREEN_WIDTH 160
#define SCALED_WIDTH 80
#define SCALED_HEIGHT 72
#define SCALED_PIXELS (SCALED_WIDTH * SCALED_HEIGHT)

#define PARTY_SIZE 6
#define MON_FIELDS 3
#define PARTY_OBS (PARTY_SIZE * MON_FIELDS)

#define BATTLE_TYPE_NONE 0
#define BATTLE_TYPE_WILD 1
#define BATTLE_TYPE_TRAINER 2
#define BATTLE_TYPE_COUNT 3
#define BATTLE_OBS (1 + 2 * MON_FIELDS)
#define BATTLE_PLAYER_MON_OFFSET 1
#define BATTLE_ENEMY_MON_OFFSET (1 + MON_FIELDS)

#define BAG_SLOTS 20
#define BAG_FIELDS 2
#define BAG_OBS (BAG_SLOTS * BAG_FIELDS)

#define BLOCK_PIXELS 16
#define BLOCKS_WIDE (SCREEN_WIDTH / BLOCK_PIXELS)
#define BLOCKS_TALL (144 / BLOCK_PIXELS)
#define PLAYER_BLOCK_COL 4
#define PLAYER_BLOCK_ROW 4

#define VISITED_MASK_OBS (BLOCKS_WIDE * BLOCKS_TALL)

#define TOTAL_OBSERVATIONS (SCALED_PIXELS + VISITED_MASK_OBS + BATTLE_OBS + PARTY_OBS + BAG_OBS)
#define VISITED_MASK_OFFSET SCALED_PIXELS
#define BATTLE_OBS_OFFSET (VISITED_MASK_OFFSET + VISITED_MASK_OBS)
#define PARTY_OBS_OFFSET (BATTLE_OBS_OFFSET + BATTLE_OBS)
#define BAG_OBS_OFFSET (PARTY_OBS_OFFSET + PARTY_OBS)

typedef enum {
    PKRED_ACTION_A = 0,
    PKRED_ACTION_B,
    PKRED_ACTION_RIGHT,
    PKRED_ACTION_LEFT,
    PKRED_ACTION_UP,
    PKRED_ACTION_DOWN,
    PKRED_ACTION_COUNT
} PokeredAction;

#define PK_BTN_A      0x01u
#define PK_BTN_B      0x02u
#define PK_BTN_SELECT 0x04u
#define PK_BTN_START  0x08u
#define PK_BTN_RIGHT  0x10u
#define PK_BTN_LEFT   0x20u
#define PK_BTN_UP     0x40u
#define PK_BTN_DOWN   0x80u

static inline unsigned pk_action_buttons(int action) {
    switch (action) {
    case PKRED_ACTION_A: return PK_BTN_A;
    case PKRED_ACTION_B: return PK_BTN_B;
    case PKRED_ACTION_RIGHT: return PK_BTN_RIGHT;
    case PKRED_ACTION_LEFT: return PK_BTN_LEFT;
    case PKRED_ACTION_UP: return PK_BTN_UP;
    case PKRED_ACTION_DOWN: return PK_BTN_DOWN;
    default: return 0;
    }
}

#endif
